import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Logo from './logo'
import SearchBar from './search-bar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Logo />
          <SearchBar />
        </nav>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
