import "./globals.css";
import { Inter } from "next/font/google";

import SearchBar from "./search-bar";
import ThemeProvider from "./theme-provider";

// import { createContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// export const ThemeContext = createContext({});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeContext.Provider value="dark"> */}
        <ThemeProvider>
          <nav>
            <Logo />
            <SearchBar />
          </nav>
          {children}
        </ThemeProvider>
        {/* </ThemeContext.Provider> */}
      </body>
    </html>
  );
}

function Logo() {
  return <img src="/next.svg" className='bg-white' />;
}
